"""empty message

Revision ID: 2bdf23f732ac
Revises: 74051705c2ff
Create Date: 2025-01-08 14:50:40.489949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdf23f732ac'
down_revision = '74051705c2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pizza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sabor', sa.String(length=80), nullable=True),
    sa.Column('ingredientes', sa.String(length=280), nullable=True),
    sa.Column('categoria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pizza')
    # ### end Alembic commands ###
