"""empty message

Revision ID: 74051705c2ff
Revises: 555fdcccdb1c
Create Date: 2024-11-26 19:56:06.566016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74051705c2ff'
down_revision = '555fdcccdb1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categoria')
    # ### end Alembic commands ###
