"""empty message

Revision ID: ff88698c4ec3
Revises: 2bdf23f732ac
Create Date: 2025-01-08 14:56:22.523997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff88698c4ec3'
down_revision = '2bdf23f732ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pizza_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pizza_ibfk_1', 'categoria', ['categoria'], ['id'])
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###
